spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        hikari:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          jdbc-url: 오라클URL
          username: 오라클ID
          password: '오라클패스워드'
#          driver-class-name: org.h2.Driver
#          jdbc-url: jdbc:h2:file:./h2database;AUTO_SERVER=TRUE
#          username: sa
#          password: 
    h2:
      console:
        enabled: true # h2 웹콘솔을 사용함
        path: /test_db # 콘솔의 경로
    devtools:
      livereload:
        enable: true