spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        hikari:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          jdbc-url: jdbc:oracle:thin:@172.22.245.146:1521:DIDMS
          username: idms
          password: 'idmspwd6#d'